package com.task2trip.android.Common

import com.task2trip.android.Model.ImageLoader.ImageCropType

class Constants {
    companion object {
        const val EXTRA_BOARD_TITLE = "EXTRA_BOARD_TITLE"
        const val EXTRA_BOARD_MESSAGE = "EXTRA_BOARD_MESSAGE"
        const val EXTRA_BOARD_IMAGE = "EXTRA_BOARD_IMAGE"
        const val EXTRA_BOARD_PAGE = "EXTRA_BOARD_PAGE"

        const val EXTRA_USER = "EXTRA_USER"
        const val EXTRA_PROFILE = "EXTRA_PROFILE"
        const val EXTRA_USER_ID = "EXTRA_USER_ID"
        const val EXTRA_USER_ROLE = "EXTRA_USER_ROLE"
        const val EXTRA_USER_TOKEN = "EXTRA_USER_TOKEN"
        const val EXTRA_USER_FIRST_NAME = "EXTRA_USER_FIRST_NAME"
        const val EXTRA_USER_LAST_NAME = "EXTRA_USER_LAST_NAME"
        const val EXTRA_USER_MIDDLE_NAME = "EXTRA_USER_MIDDLE_NAME"
        const val EXTRA_USER_IMAGE_URL = "EXTRA_USER_IMAGE_URL"
        const val EXTRA_USER_SEX = "EXTRA_USER_SEX"
        const val EXTRA_USER_BIRTHDATE = "EXTRA_USER_BIRTHDATE"
        const val EXTRA_USER_FIELD_OF_ACTIVITY = "EXTRA_USER_FIELD_OF_ACTIVITY"
        const val EXTRA_USER_INTEREST = "EXTRA_USER_INTEREST"
        const val EXTRA_USER_ABOUT = "EXTRA_USER_ABOUT"
        const val EXTRA_USER_WHY_USE = "EXTRA_USER_WHY_USE"

        const val EXTRA_FIRST_START_APP = "EXTRA_FIRST_START_APP"

        const val EXTRA_TASK = "EXTRA_TASK"
        const val EXTRA_TASK_ID = "EXTRA_TASK_ID"
        const val EXTRA_TASK_IS_EDIT = "EXTRA_TASK_IS_EDIT"
        const val EXTRA_TASK_CATEGORY_LIST = "EXTRA_TASK_CATEGORY_LIST"
        const val EXTRA_TASK_CATEGORY_SELECTED_POSITION = "EXTRA_TASK_CATEGORY_SELECTED_POSITION"
        const val EXTRA_TASK_SEARCH_COUNTRY_CITY = "EXTRA_TASK_SEARCH_COUNTRY_CITY"
        const val EXTRA_TASK_SEARCH_STATUS = "EXTRA_TASK_SEARCH_STATUS"

        const val EXTRA_OFFER = "EXTRA_OFFER"
        const val EXTRA_OFFER_IS_SHOW_MY = "EXTRA_OFFER_IS_SHOW_MY"

        const val EXTRA_DIALOG_TITLE = "EXTRA_DIALOG_TITLE"
        const val EXTRA_DIALOG_MESSAGE = "EXTRA_DIALOG_MESSAGE"
        const val EXTRA_DIALOG_DESCRIPTION = "EXTRA_DIALOG_DESCRIPTION"
        const val EXTRA_DIALOG_POSITIVE_BUTTON_TITLE = "EXTRA_DIALOG_POSITIVE_BUTTON_TITLE"
        const val EXTRA_DIALOG_NEGATIVE_BUTTON_TITLE = "EXTRA_DIALOG_NEGATIVE_BUTTON_TITLE"
        const val EXTRA_DIALOG_IS_SHOW_TIME = "EXTRA_DIALOG_IS_SHOW_TIME"
        const val EXTRA_DIALOG_INIT_DATE_TIME = "EXTRA_DIALOG_INIT_DATE_TIME"
        const val EXTRA_DIALOG_PHOTO_SOURCE = "EXTRA_DIALOG_PHOTO_SOURCE"
        const val EXTRA_DIALOG_IS_START = "EXTRA_DIALOG_IS_START"

        const val EXTRA_IS_MESSAGE = "EXTRA_IS_MESSAGE"
        const val EXTRA_MESSAGE_TEXT = "EXTRA_MESSAGE_TEXT"
        const val EXTRA_SELECTED_DATE_TIME = "EXTRA_SELECTED_DATE_TIME"

        const val EXTRA_SELECTED_PAGE = "EXTRA_SELECTED_PAGE"
        const val EXTRA_USER_LEVEL_UP = "EXTRA_USER_LEVEL_UP"
        const val EXTRA_PHOTO_SOURCE_CAMERA = "Фотокамера"
        const val EXTRA_PHOTO_SOURCE_STORAGE = "На диске"

        const val REQUEST_PERMISSION_STORAGE = 248
        const val REQUEST_PERMISSION_PHOTO = 249
        const val REQUEST_STORAGE_BROWSER = 250
        const val REQUEST_CAMERA_PHOTO = 251
        const val REQUEST_DIALOG_CAMERA_SOURCE = 252
        const val REQUEST_DIALOG_DATE_TIME = 253
        const val REQUEST_DIALOG_SIMPLE = 254
        const val REQUEST_DIALOG_CATEGORY = 255

        const val MIN_EMAIL_LENGTH = 8
        const val MIN_PASSWORD_LENGTH = 5
        const val MIN_NAME_LENGTH = 3

        const val FILE_NAME_AVATAR = "user_avatar.jpg"
        const val TIME_PATTERN_DDMMYYYY = "dd.MM.yyyy"

        val DEFAULT_CROP_TYPE = ImageCropType.CROP_ROUNDED
    }
}