package com.task2trip.android.Common

class Constants {
    companion object {
        const val EXTRA_BOARD_TITLE = "EXTRA_BOARD_TITLE"
        const val EXTRA_BOARD_MESSAGE = "EXTRA_BOARD_MESSAGE"
        const val EXTRA_BOARD_IMAGE = "EXTRA_BOARD_IMAGE"
        const val EXTRA_BOARD_PAGE = "EXTRA_BOARD_PAGE"

        const val EXTRA_USER = "EXTRA_USER"
        const val EXTRA_USER_ID = "EXTRA_USER_ID"
        const val EXTRA_USER_LOGIN = "EXTRA_USER_LOGIN"
        const val EXTRA_USER_NAME = "EXTRA_USER_NAME"
        const val EXTRA_USER_EMAIL = "EXTRA_USER_EMAIL"
        const val EXTRA_USER_ROLE = "EXTRA_USER_ROLE"
        const val EXTRA_USER_TOKEN = "EXTRA_USER_TOKEN"
        const val EXTRA_USER_IMAGE_URL = "EXTRA_USER_IMAGE_URL"

        const val EXTRA_FIRST_START_APP = "EXTRA_FIRST_START_APP"
        const val EXTRA_LAYOUT_RESOURCE = "EXTRA_LAYOUT_RESOURCE"

        const val EXTRA_TASK = "EXTRA_TASK"
        const val EXTRA_TASK_ID = "EXTRA_TASK_ID"
        const val EXTRA_TASK_IS_EDIT = "EXTRA_TASK_IS_EDIT"
        const val EXTRA_TASK_CATEGORY_LIST = "EXTRA_TASK_CATEGORY_LIST"
        const val EXTRA_TASK_CATEGORY_SELECTED_POSITION = "EXTRA_TASK_CATEGORY_SELECTED_POSITION"
        const val EXTRA_TASK_SEARCH_CATEGORY = "EXTRA_TASK_SEARCH_CATEGORY"
        const val EXTRA_TASK_SEARCH_COUNTRY_CITY = "EXTRA_TASK_SEARCH_COUNTRY_CITY"
        const val EXTRA_TASK_SEARCH_STATUS = "EXTRA_TASK_SEARCH_STATUS"

        const val EXTRA_OFFER = "EXTRA_OFFER"

        const val EXTRA_DIALOG_TITLE = "EXTRA_DIALOG_TITLE"
        const val EXTRA_DIALOG_MESSAGE = "EXTRA_DIALOG_MESSAGE"

        const val EXTRA_IS_MESSAGE = "EXTRA_IS_MESSAGE"
        const val EXTRA_MESSAGE_TEXT = "EXTRA_MESSAGE_TEXT"
    }
}